"""empty message

Revision ID: 187577ac3a05
Revises: dd0f08a7546e
Create Date: 2021-08-22 13:58:05.611138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187577ac3a05'
down_revision = 'dd0f08a7546e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comments',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comments',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
